language:
- python

python:
- "3.9"

install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install black
  - pip install flake8
  - pip install coveralls


script:
  - black --check .
  - flake .
